### ISSUE TITLE
Unable to update profile when signed in via GitHub

### ISSUE THREAD

**Issue by OybekBabaev** [falsenotes-dev/website#60]
**Describe the bug**
So I wanted to set up a bio for my profile, but the website apparently does not allow me to do so if the email section is left empty. But I can't fill it in! The drop-down list labelled "Your public email address on GitHub" has no entries.
Plz fix!

**Screenshots**
![Screenshot (626)](https://github.com/falsenotes-dev/website/assets/88846068/0d51abb2-e62b-48b6-8a09-0704ebec3210)

**Additional context**
Come on, I just want to set a cool bio for once.

**Comment by yusupovbg** [comment]
The settings page is currently a demo version; we're actively developing it.

**Comment by yusupovbg** [comment]
Fixed
#70 
#71
